export const AI_API_KEY_HEADER = 'x-job-seeker-agent-ai-key'
export const AI_BASE_URL_HEADER = 'x-job-seeker-agent-ai-base-url'
export const AI_MODEL_HEADER = 'x-job-seeker-agent-ai-model'
export const LEGACY_AI_API_KEY_HEADER = 'x-resume-os-ai-key'
export const LEGACY_AI_BASE_URL_HEADER = 'x-resume-os-ai-base-url'
export const LEGACY_AI_MODEL_HEADER = 'x-resume-os-ai-model'
